version: 2


jobs:
  build:
    docker: 
      - image: cimg/node:16.14
    steps:
      - checkout
      - yarn install
  test:
    steps:
      - yarn run test

workflows:
  version: 2
  build_and_test:
    jobs: 
      - build
      - test:
          requires:
            - build